# Generated by Django 4.2.4 on 2024-02-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_alter_event_info_host_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_info',
            name='Host_name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
