# Generated by Django 4.2.4 on 2024-03-06 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0009_alter_chat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_app.event_info'),
        ),
    ]
