# Generated by Django 4.2.4 on 2024-03-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0011_rename_name_chat_host_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='Host_name',
        ),
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
